AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Announcements API application

Globals:
  Function: 
    Environment:
      Variables:
        DBNAME: announcements
        REGION: us-east-1
        QLIMIT: 1000

Resources:
  AnnouncementsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota: 
            Limit: 1000000
            Period: MONTH
          Throttle: 
            BurstLimit: 500
            RateLimit: 1000
          UsagePlanName: premium-plan

  Announcements:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Policies: [CloudWatchFullAccess, AmazonDynamoDBFullAccess]
      Timeout: 60
      MemorySize: 512
      Events:
        GetList:
          Type: Api
          Properties:
            RestApiId: !Ref AnnouncementsAPI
            Path: /announcements
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref AnnouncementsAPI
            Path: /announcement
            Method: POST
        GetByTitle:
          Type: Api
          Properties:
            RestApiId: !Ref AnnouncementsAPI
            Path: /announcement
            Method: GET
  
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: announcements
